services:

  greencheck-db:

    image: postgres:16

    container_name: greencheck-postgres

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - greencheck-db-data:/var/lib/postgresql/data


  greencheck-odoo:

    image: odoo:19.0

    container_name: greencheck-odoo

    depends_on:
      - greencheck-db

    ports:
      - "8070:8069"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:

      - ./addons:/mnt/extra-addons

      - ./config:/etc/odoo

      - greencheck-web-data:/var/lib/odoo


volumes:

  greencheck-db-data:

  greencheck-web-data:
