[options]
admin_passwd = $pbkdf2-sha512$600000$Occ4Z4xxzvl/r1XqndO69w$7UloOXpkYyZ0mxa72hXMRxmtLqPfVarswIkS/k.kcvvGSzBqNtfG.3lHK.9Q1VOZB9pdqLIckcEIiq1A0GrACg
db_host = greencheck-db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = greencheck

addons_path = 
	/usr/lib/python3/dist-packages/odoo/addons,
	/mnt/extra-addons

